###register request

post http://localhost:3000/auth/register
Content-Type: application/json

{
    "username" : "asdgasdg.dfgjdfg",
    "email" : "sdfhsdgsds@yahoo.com",
    "mobile" : "09120597067",
    "password" : "sdfh",
    "confirm_password" : "sdfh"
}